### ISSUE TITLE
Home Page Autoplay

### ISSUE THREAD

**Issue by MoonTahoe** [eveporcello/moonhighway#28]
Add an option to Autoplay and loop the home page animations. We can put the site up on screens before we teach/speak.

* Add Autoplay
* (optional) Add Title Screen First screen is title of the talk?

**Comment by eveporcello** [comment]
console autoplay(3000) will autoscroll homepage for 3 seconds.

* Google Analytics doesn't record while autoplay is happening
* Execute autoplay() to stop
